### PR TITLE
Fix getMainRequest incompatible with symfony 4.4

### LINKED ISSUE #106: getMainRequest not compatible with SF 4.4.37
Hi,

Thanks for this bundle!

It seems there is an issue on https://github.com/OpenConext/Stepup-saml-bundle/blob/690d1ba2aeeef536f26e5c599375d6d4b1d49007/src/Entity/HostedEntities.php#L145 

getMainRequest() is not a valid method for SF4.4 (https://github.com/symfony/symfony/blob/v4.4.37/src/Symfony/Component/HttpFoundation/RequestStack.php) I guess it should be better to protect the call with method_exists and calling getMasterRequest() otherwise, no?

Didn't have time right now to check if there is other parts concerned but I can help if needed.

Thanks!

### PR DESCRIPTION
**Pull request by epidoux**
Fix #106

### CODE REVIEW

**Comment by phavekes** [comment]
Thank you for this PR.

Could you rebase it to develop to enable automatic testing?

Also there are two minor code-style errors to be addressed: 

```
phpcs-ci:
     [exec] 
     [exec] FILE: ...uild/OpenConext/Stepup-saml-bundle/src/Entity/HostedEntities.php
     [exec] ----------------------------------------------------------------------
     [exec] FOUND 2 ERRORS AFFECTING 2 LINES
     [exec] ----------------------------------------------------------------------
     [exec]  147 | ERROR | [x] Expected 1 space after closing brace; newline
     [exec]      |       |     found
     [exec]  148 | ERROR | [x] Inline control structures are not allowed
     [exec] ----------------------------------------------------------------------
     [exec] PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
     [exec] ----------------------------------------------------------------------
     [exec] 
     [exec] Time: 1.85 secs; Memory: 10MB
     [exec] 
```

**Comment by MKodde** [comment]
Thanks for your contribution @epidoux 

I was looking at this change and started digging into this issue. What I found was:
As of SF 4.4 the getMainRequest method is part of the symfony/framework-bundle. And the getMasterRequest has been deprecated. Are you on that version of the framework bundle? If you are, this change should not be necessary right?  

Lets say we cant to support Symfony < 4.4. Then your change makes perfect sense. However. We are inclined to drop support for older, no longer maintained Symfony versions.

And finally regarding your code style: in my personal day to day as a software developer. I try to avoid `else` statements. These article helped me to work around this. Consider implementing a fix for this.

https://medium.com/swlh/stop-using-if-else-statements-f4d2323e6e4
https://janalmazora.medium.com/how-to-prevent-using-if-else-statements-in-your-code-7e05e43afde

**Comment by epidoux** [comment]
Hi @MKodde,

Thanks for your answer. My pull request is not needed indeed if you drop support of older sf version. However, as this bundle has a requirement in composer only with "symfony/framework-bundle" and a strong dependency on the method getMainRequest of RequestStack (which is part of symfony/http-foundation component), I think it is necessary to add "symfony/http-foundation":"^5.0" as a requirement. If you look into https://packagist.org/packages/symfony/framework-bundle#v4.4.37, you can still use both 4.4 & 5.0 versions of http-foundation.

**Comment by thijskh** [comment]
I found out that this change is indeed required also for us, as SF 4.4 does not include getMainRequest(). I'm merging it for now as it's a straightforward fix and keeps BC with these 4.4 apps instead of requiring to update to 5.1+ everywhere.

**Pull request merged**
