### PR TITLE
Add knowledge about attribute eduPersonScopedAffiliation

### PR DESCRIPTION
**Pull request by thijskh**

### CODE REVIEW

**Comment by thijskh** [comment]
Thanks for the catch. I was originally working on an old version of the library and didn't notice this attribute had been added since. I've now fixed the entry instead. While at it, I've cleaned up some obsolete attributes.

**Comment by pablothedude** [comment]
@MKodde no, nothing to add

**Comment by MKodde** [comment]
Rebased, and merged!

**Comment by thijskh** [comment]
I think the rebase introduced this change by mistake:
https://github.com/OpenConext/Stepup-saml-bundle/pull/84/commits/5f1c491961cad4948dc83043afa92719122ed999#diff-6bb19e65272e3f9fcd5dcb8997cc165fR225

**Comment by MKodde** [comment]
Oops, my bad, fixing that on develop

**Pull request merged**
