### PR TITLE
Allow setting ForceAuthn on AuthnRequest

### PR DESCRIPTION
**Pull request by MKodde**
For now we could only get the state of the ForceAuthn flag. But where
not able to set it.

https://www.pivotaltracker.com/story/show/171101458

### CODE REVIEW

**Comment by MKodde** [comment]
> Shouldn't this be resolved in the `\Surfnet\SamlBundle\SAML2\AuthnRequestFactory`? That way immutability will be preserved?

It could be achieved in the factory, yes. As this is corner case, I personally opted for simply adding a setter on the entity itself. Are you aware that the AuthnRequest is not an immutable object?

**Comment by MKodde** [comment]
As an alternative I'm willing to update the `AuthnRequestFactory::createNewRequest`, adding a third optional parameter which controls whether or not the AuthnRequest should force authentication. That way the AuthnRequest will not become more mutable.

**Comment by pablothedude** [comment]
I think because it's a corner case would only justify the opposite of making properties mutable.

Because there are some setters doesn't justify making more methods mutable. The factory should be responsible for the initialization of objects so I think that would be a better place. The 'ForceAuthn' property could then come from the `AzureMfaIdentityProvider`.

Why don't you want to implement this in the `\Surfnet\AzureMfa\Application\Service\AzureMfaService::createAuthnRequest` as a property on the `IdentityProvider`. I don't see why this won't work because for other Stepup projects there are `SAML2\Configuration\IdentityProvider` implementations for IdentityProvider, ServiceProvider and HostedEntities and for example AzureMFA has it's own implementation of the `SAML2\Configuration\IdentityProvider` (`\Surfnet\AzureMfa\Infrastructure\Entity\AzureMfaIdentityProvider`).

**Comment by MKodde** [comment]
Instead of adding the setter, I went with a third parameter on the `createNewRequest` factory method. I do not agree that an SP/IdP configuration should determine/manipulate the behavior of the AuthNRequest to that extent.

Can you live with this?

**Comment by pablothedude** [comment]
Off course I can live with this, it was just a thing to keep in mind. The only thing I don't like is that the threshold will be lowered to just add configuration parameters to the method when needed. Just like a command is used in a commandhandler to prevent adding parameters all over the place.

**Pull request merged**
